// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {state} from '../models';
import {main} from '../models';
import {claude} from '../models';
import {git} from '../models';
import {iterm} from '../models';
import {health} from '../models';
import {structure} from '../models';
import {gmail} from '../models';

export function AddKanbanComment(arg1:string,arg2:string,arg3:string,arg4:string):Promise<state.KanbanComment>;

export function AddonSendEmail(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:Array<string>):Promise<void>;

export function AddonStorageAll(arg1:string):Promise<Record<string, string>>;

export function AddonStorageDelete(arg1:string,arg2:string):Promise<void>;

export function AddonStorageSet(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddonsList():Promise<main.AddonsInfo>;

export function AddonsReload():Promise<main.AddonsInfo>;

export function ArchiveNotification(arg1:string):Promise<void>;

export function CalendarConnect(arg1:string,arg2:string):Promise<string>;

export function CalendarDisconnect(arg1:string):Promise<void>;

export function CalendarSetShared(arg1:string,arg2:Array<string>):Promise<void>;

export function CheckDependencies():Promise<Array<main.DependencyStatus>>;

export function ClearTerminalAccount(arg1:string):Promise<void>;

export function CloseITermTab(arg1:number,arg2:number):Promise<void>;

export function CloseITermTabBySessionID(arg1:string):Promise<void>;

export function ConfirmDialog(arg1:string,arg2:string):Promise<boolean>;

export function CreateDirectory(arg1:string):Promise<void>;

export function CreateGlobalPrompt(arg1:state.Prompt):Promise<state.Prompt>;

export function CreateITermTab(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateITermTabWithRunner(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CreateProject(arg1:string,arg2:string):Promise<state.ProjectState>;

export function CreateProjectGroup(arg1:string,arg2:string,arg3:string):Promise<state.ProjectGroup>;

export function CreateProjectTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:Array<string>):Promise<state.TaskState>;

export function CreatePrompt(arg1:string,arg2:state.Prompt):Promise<state.Prompt>;

export function CreatePromptCategory(arg1:string,arg2:string,arg3:boolean):Promise<state.PromptCategory>;

export function DeleteAutomationRule(arg1:string):Promise<void>;

export function DeleteCustomHealthCheck(arg1:string):Promise<void>;

export function DeleteDashboard(arg1:string):Promise<void>;

export function DeleteGlobalPrompt(arg1:string):Promise<void>;

export function DeleteKanbanColumn(arg1:string,arg2:string):Promise<void>;

export function DeleteKanbanTask(arg1:string,arg2:string):Promise<void>;

export function DeleteNotification(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteProjectGroup(arg1:string):Promise<void>;

export function DeleteProjectTask(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<void>;

export function DeletePrompt(arg1:string,arg2:string):Promise<void>;

export function DeletePromptCategory(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DeleteRunner(arg1:string):Promise<void>;

export function ExpandPath(arg1:string):Promise<string>;

export function FocusITerm():Promise<void>;

export function GetActiveProject():Promise<string>;

export function GetAgentSkills():Promise<Array<main.AgentSkillInfo>>;

export function GetAllViewFontSize():Promise<number>;

export function GetAppVersion():Promise<string>;

export function GetAutomationRules():Promise<Array<state.AutomationRule>>;

export function GetAutomationRuns(arg1:number):Promise<Array<state.AutomationRun>>;

export function GetCalendarConfig():Promise<Array<main.CalendarAccountInfo>>;

export function GetClaudeAccounts():Promise<Array<state.ClaudeAccount>>;

export function GetClaudeSessions():Promise<Array<claude.SessionInfo>>;

export function GetDashboardFullscreen():Promise<boolean>;

export function GetDashboards():Promise<Array<state.Dashboard>>;

export function GetDefaultColors():Promise<Array<string>>;

export function GetDefaultIcons():Promise<Array<string>>;

export function GetDefaultRunner():Promise<string>;

export function GetElevenLabsAPIKey():Promise<string>;

export function GetGitChangedFiles(arg1:string):Promise<Array<git.ChangedFile>>;

export function GetGitCurrentBranch(arg1:string):Promise<string>;

export function GetGitFileDiff(arg1:string,arg2:string):Promise<git.FileDiff>;

export function GetGitStatus(arg1:string):Promise<Record<string, number>>;

export function GetGlobalPromptCategories():Promise<Array<state.PromptCategory>>;

export function GetGlobalPromptPrefix():Promise<string>;

export function GetGlobalPromptSuffix():Promise<string>;

export function GetGlobalPrompts():Promise<Array<state.Prompt>>;

export function GetGmailConfig():Promise<main.GmailConfig>;

export function GetHealthLibrary():Promise<main.HealthLibrary>;

export function GetHealthSelection(arg1:string):Promise<Array<string>>;

export function GetHiddenModules():Promise<Array<string>>;

export function GetITermSessionContents(arg1:number):Promise<string>;

export function GetITermSessionContentsByID(arg1:string,arg2:number):Promise<string>;

export function GetITermSessionInfo():Promise<iterm.SessionInfo>;

export function GetITermStatus():Promise<iterm.ITermStatus>;

export function GetJiraSettings():Promise<state.JiraSettings>;

export function GetKanban(arg1:string):Promise<main.KanbanBoard>;

export function GetManualChecks(arg1:string):Promise<Record<string, health.ManualCheckState>>;

export function GetModuleOrder():Promise<Array<string>>;

export function GetNotes(arg1:string):Promise<string>;

export function GetNotifications(arg1:boolean):Promise<Array<state.Notification>>;

export function GetPinnedTerminals():Promise<Record<string, string>>;

export function GetPomodoroSettings():Promise<state.PomodoroSettings>;

export function GetProject(arg1:string):Promise<state.ProjectState>;

export function GetProjectDependencies(arg1:string):Promise<Record<string, string>>;

export function GetProjectFolderHierarchy(arg1:string):Promise<structure.FileNode>;

export function GetProjectGroups():Promise<Array<state.ProjectGroup>>;

export function GetProjectPrompts(arg1:string):Promise<Array<state.Prompt>>;

export function GetProjectStructure(arg1:string):Promise<structure.FileNode>;

export function GetProjectWidgets(arg1:string):Promise<Array<string>>;

export function GetProjects():Promise<Array<state.ProjectState>>;

export function GetPromptCategories(arg1:string):Promise<Array<state.PromptCategory>>;

export function GetRunners():Promise<Array<state.Runner>>;

export function GetSelectedHealthReport(arg1:string):Promise<health.ProjectHealthReport>;

export function GetState():Promise<state.AppState>;

export function GetTerminalAccounts():Promise<Record<string, string>>;

export function GetTerminalFontSize():Promise<number>;

export function GetTerminalNameOverrides():Promise<Record<string, string>>;

export function GetTerminalRunners():Promise<Record<string, string>>;

export function GetTerminalTheme():Promise<string>;

export function GetTranscriptionEngine():Promise<string>;

export function GetUnreadNotificationCount():Promise<number>;

export function GetVoiceAutoSubmit():Promise<boolean>;

export function GetVoiceLang():Promise<string>;

export function GetWidgetSettings():Promise<state.WidgetSettings>;

export function GmailAddAccount(arg1:string,arg2:string):Promise<string>;

export function GmailCreateDraft(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<string>):Promise<string>;

export function GmailDeleteDraft(arg1:string,arg2:string):Promise<void>;

export function GmailGetAttachment(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GmailGetSignature(arg1:string):Promise<string>;

export function GmailGetThread(arg1:string,arg2:string):Promise<gmail.ThreadDetail>;

export function GmailInboxUnread(arg1:string):Promise<number>;

export function GmailInstallMcp():Promise<string>;

export function GmailListContacts(arg1:string):Promise<Array<gmail.Contact>>;

export function GmailListLabels(arg1:string):Promise<Array<gmail.Label>>;

export function GmailListThreadDrafts(arg1:string,arg2:string):Promise<Array<gmail.DraftInfo>>;

export function GmailListThreads(arg1:string,arg2:string,arg3:string,arg4:string):Promise<gmail.ThreadPage>;

export function GmailMcpInstalled():Promise<boolean>;

export function GmailModifyThread(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<string>):Promise<void>;

export function GmailOpenAttachment(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GmailPickAttachments():Promise<Array<string>>;

export function GmailReauthAccount(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GmailRemoveAccount(arg1:string):Promise<void>;

export function GmailSaveAttachment(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GmailSendDraft(arg1:string,arg2:string):Promise<void>;

export function GmailSendMessage(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<string>):Promise<void>;

export function GmailSetAccountMcp(arg1:string,arg2:boolean):Promise<void>;

export function GmailTrashThread(arg1:string,arg2:string):Promise<void>;

export function GmailUntrashThread(arg1:string,arg2:string):Promise<void>;

export function GmailUpdateDraft(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:Array<string>):Promise<void>;

export function IncrementPromptUsage(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function IsDevMode():Promise<boolean>;

export function IsGitRepo(arg1:string):Promise<boolean>;

export function KillClaudeSession(arg1:number,arg2:boolean):Promise<void>;

export function LaunchITerm():Promise<void>;

export function ListProjectRepos(arg1:string):Promise<Array<main.ProjectRepo>>;

export function Log(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<void>;

export function MarkNotificationRead(arg1:string):Promise<void>;

export function MoveKanbanTask(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function OpenAddonsDir():Promise<void>;

export function OpenProjectTask(arg1:string,arg2:string):Promise<state.TaskState>;

export function OpenTmuxInITerm(arg1:string):Promise<void>;

export function PasteClipboardToSession(arg1:string):Promise<void>;

export function PathExists(arg1:string):Promise<boolean>;

export function ReadFileContent(arg1:string):Promise<string>;

export function RenameITermTab(arg1:number,arg2:number,arg3:string):Promise<void>;

export function RenameITermTabBySessionID(arg1:string,arg2:string):Promise<void>;

export function RequestStyledHistory(arg1:string):Promise<void>;

export function ResetVoiceRecognition():Promise<void>;

export function RunAutomationRule(arg1:string):Promise<state.AutomationRun>;

export function SaveAutomationRule(arg1:state.AutomationRule):Promise<state.AutomationRule>;

export function SaveCustomHealthCheck(arg1:state.CustomHealthCheck):Promise<state.CustomHealthCheck>;

export function SaveDashboard(arg1:state.Dashboard):Promise<state.Dashboard>;

export function SaveFileContent(arg1:string,arg2:string):Promise<void>;

export function SaveKanbanColumns(arg1:string,arg2:Array<state.KanbanColumn>):Promise<void>;

export function SaveNotes(arg1:string,arg2:string):Promise<void>;

export function SavePomodoroSettings(arg1:number,arg2:number):Promise<void>;

export function SaveRunner(arg1:state.Runner):Promise<state.Runner>;

export function SaveScreenshot(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function SendITermSpecialKey(arg1:string,arg2:string):Promise<void>;

export function SetActiveProject(arg1:string):Promise<void>;

export function SetAddonEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetAgentSkillEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetAllViewFontSize(arg1:number):Promise<void>;

export function SetAutomationRuleEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetClaudeAccounts(arg1:Array<state.ClaudeAccount>):Promise<void>;

export function SetDashboardFullscreen(arg1:boolean):Promise<void>;

export function SetDefaultRunner(arg1:string):Promise<void>;

export function SetElevenLabsAPIKey(arg1:string):Promise<void>;

export function SetGlobalPromptPrefix(arg1:string):Promise<void>;

export function SetGlobalPromptSuffix(arg1:string):Promise<void>;

export function SetGmailConfig(arg1:boolean,arg2:string,arg3:string):Promise<void>;

export function SetGmailMcpEnabled(arg1:boolean):Promise<void>;

export function SetHealthSelection(arg1:string,arg2:Array<string>):Promise<void>;

export function SetHiddenModules(arg1:Array<string>):Promise<void>;

export function SetJiraSettings(arg1:state.JiraSettings):Promise<void>;

export function SetManualCheck(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<void>;

export function SetModuleOrder(arg1:Array<string>):Promise<void>;

export function SetPinnedTerminal(arg1:string,arg2:string):Promise<void>;

export function SetProjectJira(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetProjectWidgets(arg1:string,arg2:Array<string>):Promise<void>;

export function SetTermViewSize(arg1:number,arg2:number):Promise<void>;

export function SetTerminalAccount(arg1:string,arg2:string):Promise<void>;

export function SetTerminalFontSize(arg1:number):Promise<void>;

export function SetTerminalNameOverride(arg1:string,arg2:string):Promise<void>;

export function SetTerminalRunner(arg1:string,arg2:string):Promise<void>;

export function SetTerminalTheme(arg1:string):Promise<void>;

export function SetTranscriptionEngine(arg1:string):Promise<void>;

export function SetVoiceAutoSubmit(arg1:boolean):Promise<void>;

export function SetVoiceLang(arg1:string):Promise<void>;

export function SetWidgetSettings(arg1:state.WidgetSettings):Promise<void>;

export function StartVoiceRecognition(arg1:string):Promise<string>;

export function StopVoiceRecognition():Promise<void>;

export function SwitchITermTab(arg1:number,arg2:number):Promise<void>;

export function SwitchITermTabBySessionID(arg1:string):Promise<void>;

export function SyncJiraBoard(arg1:string):Promise<main.JiraSyncResult>;

export function TestJiraConnection(arg1:state.JiraSettings):Promise<string>;

export function TogglePromptPinned(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function UnwatchITermSession():Promise<void>;

export function UpdateGlobalPrompt(arg1:string,arg2:state.Prompt):Promise<void>;

export function UpdateProject(arg1:state.ProjectState):Promise<void>;

export function UpdateProjectGroup(arg1:state.ProjectGroup):Promise<void>;

export function UpdateProjectTask(arg1:string,arg2:state.TaskState):Promise<void>;

export function UpdatePrompt(arg1:string,arg2:string,arg3:state.Prompt):Promise<void>;

export function UpsertKanbanTask(arg1:string,arg2:state.KanbanTask):Promise<state.KanbanTask>;

export function WatchITermSession(arg1:string):Promise<string>;

export function WriteITermText(arg1:string,arg2:boolean):Promise<void>;

export function WriteITermTextBySessionID(arg1:string,arg2:string,arg3:boolean):Promise<void>;
