// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKanbanComment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddKanbanComment'](arg1, arg2, arg3, arg4);
}

export function AddonSendEmail(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddonSendEmail'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function AddonStorageAll(arg1) {
  return window['go']['main']['App']['AddonStorageAll'](arg1);
}

export function AddonStorageDelete(arg1, arg2) {
  return window['go']['main']['App']['AddonStorageDelete'](arg1, arg2);
}

export function AddonStorageSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddonStorageSet'](arg1, arg2, arg3);
}

export function AddonsList() {
  return window['go']['main']['App']['AddonsList']();
}

export function AddonsReload() {
  return window['go']['main']['App']['AddonsReload']();
}

export function ArchiveNotification(arg1) {
  return window['go']['main']['App']['ArchiveNotification'](arg1);
}

export function CalendarConnect(arg1, arg2) {
  return window['go']['main']['App']['CalendarConnect'](arg1, arg2);
}

export function CalendarDisconnect(arg1) {
  return window['go']['main']['App']['CalendarDisconnect'](arg1);
}

export function CalendarSetShared(arg1, arg2) {
  return window['go']['main']['App']['CalendarSetShared'](arg1, arg2);
}

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function ClearTerminalAccount(arg1) {
  return window['go']['main']['App']['ClearTerminalAccount'](arg1);
}

export function CloseITermTab(arg1, arg2) {
  return window['go']['main']['App']['CloseITermTab'](arg1, arg2);
}

export function CloseITermTabBySessionID(arg1) {
  return window['go']['main']['App']['CloseITermTabBySessionID'](arg1);
}

export function ConfirmDialog(arg1, arg2) {
  return window['go']['main']['App']['ConfirmDialog'](arg1, arg2);
}

export function CreateDirectory(arg1) {
  return window['go']['main']['App']['CreateDirectory'](arg1);
}

export function CreateGlobalPrompt(arg1) {
  return window['go']['main']['App']['CreateGlobalPrompt'](arg1);
}

export function CreateITermTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateITermTab'](arg1, arg2, arg3);
}

export function CreateITermTabWithRunner(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateITermTabWithRunner'](arg1, arg2, arg3, arg4);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function CreateProjectGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateProjectGroup'](arg1, arg2, arg3);
}

export function CreateProjectTask(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateProjectTask'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreatePrompt(arg1, arg2) {
  return window['go']['main']['App']['CreatePrompt'](arg1, arg2);
}

export function CreatePromptCategory(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreatePromptCategory'](arg1, arg2, arg3);
}

export function DeleteAutomationRule(arg1) {
  return window['go']['main']['App']['DeleteAutomationRule'](arg1);
}

export function DeleteCustomHealthCheck(arg1) {
  return window['go']['main']['App']['DeleteCustomHealthCheck'](arg1);
}

export function DeleteDashboard(arg1) {
  return window['go']['main']['App']['DeleteDashboard'](arg1);
}

export function DeleteGlobalPrompt(arg1) {
  return window['go']['main']['App']['DeleteGlobalPrompt'](arg1);
}

export function DeleteKanbanColumn(arg1, arg2) {
  return window['go']['main']['App']['DeleteKanbanColumn'](arg1, arg2);
}

export function DeleteKanbanTask(arg1, arg2) {
  return window['go']['main']['App']['DeleteKanbanTask'](arg1, arg2);
}

export function DeleteNotification(arg1) {
  return window['go']['main']['App']['DeleteNotification'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteProjectGroup(arg1) {
  return window['go']['main']['App']['DeleteProjectGroup'](arg1);
}

export function DeleteProjectTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteProjectTask'](arg1, arg2, arg3, arg4);
}

export function DeletePrompt(arg1, arg2) {
  return window['go']['main']['App']['DeletePrompt'](arg1, arg2);
}

export function DeletePromptCategory(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeletePromptCategory'](arg1, arg2, arg3);
}

export function DeleteRunner(arg1) {
  return window['go']['main']['App']['DeleteRunner'](arg1);
}

export function ExpandPath(arg1) {
  return window['go']['main']['App']['ExpandPath'](arg1);
}

export function FocusITerm() {
  return window['go']['main']['App']['FocusITerm']();
}

export function GetActiveProject() {
  return window['go']['main']['App']['GetActiveProject']();
}

export function GetAgentSkills() {
  return window['go']['main']['App']['GetAgentSkills']();
}

export function GetAllViewFontSize() {
  return window['go']['main']['App']['GetAllViewFontSize']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAutomationRules() {
  return window['go']['main']['App']['GetAutomationRules']();
}

export function GetAutomationRuns(arg1) {
  return window['go']['main']['App']['GetAutomationRuns'](arg1);
}

export function GetCalendarConfig() {
  return window['go']['main']['App']['GetCalendarConfig']();
}

export function GetClaudeAccounts() {
  return window['go']['main']['App']['GetClaudeAccounts']();
}

export function GetClaudeSessions() {
  return window['go']['main']['App']['GetClaudeSessions']();
}

export function GetDashboardFullscreen() {
  return window['go']['main']['App']['GetDashboardFullscreen']();
}

export function GetDashboards() {
  return window['go']['main']['App']['GetDashboards']();
}

export function GetDefaultColors() {
  return window['go']['main']['App']['GetDefaultColors']();
}

export function GetDefaultIcons() {
  return window['go']['main']['App']['GetDefaultIcons']();
}

export function GetDefaultRunner() {
  return window['go']['main']['App']['GetDefaultRunner']();
}

export function GetElevenLabsAPIKey() {
  return window['go']['main']['App']['GetElevenLabsAPIKey']();
}

export function GetGitChangedFiles(arg1) {
  return window['go']['main']['App']['GetGitChangedFiles'](arg1);
}

export function GetGitCurrentBranch(arg1) {
  return window['go']['main']['App']['GetGitCurrentBranch'](arg1);
}

export function GetGitFileDiff(arg1, arg2) {
  return window['go']['main']['App']['GetGitFileDiff'](arg1, arg2);
}

export function GetGitStatus(arg1) {
  return window['go']['main']['App']['GetGitStatus'](arg1);
}

export function GetGlobalPromptCategories() {
  return window['go']['main']['App']['GetGlobalPromptCategories']();
}

export function GetGlobalPromptPrefix() {
  return window['go']['main']['App']['GetGlobalPromptPrefix']();
}

export function GetGlobalPromptSuffix() {
  return window['go']['main']['App']['GetGlobalPromptSuffix']();
}

export function GetGlobalPrompts() {
  return window['go']['main']['App']['GetGlobalPrompts']();
}

export function GetGmailConfig() {
  return window['go']['main']['App']['GetGmailConfig']();
}

export function GetHealthLibrary() {
  return window['go']['main']['App']['GetHealthLibrary']();
}

export function GetHealthSelection(arg1) {
  return window['go']['main']['App']['GetHealthSelection'](arg1);
}

export function GetHiddenModules() {
  return window['go']['main']['App']['GetHiddenModules']();
}

export function GetITermSessionContents(arg1) {
  return window['go']['main']['App']['GetITermSessionContents'](arg1);
}

export function GetITermSessionContentsByID(arg1, arg2) {
  return window['go']['main']['App']['GetITermSessionContentsByID'](arg1, arg2);
}

export function GetITermSessionInfo() {
  return window['go']['main']['App']['GetITermSessionInfo']();
}

export function GetITermStatus() {
  return window['go']['main']['App']['GetITermStatus']();
}

export function GetJiraSettings() {
  return window['go']['main']['App']['GetJiraSettings']();
}

export function GetKanban(arg1) {
  return window['go']['main']['App']['GetKanban'](arg1);
}

export function GetManualChecks(arg1) {
  return window['go']['main']['App']['GetManualChecks'](arg1);
}

export function GetModuleOrder() {
  return window['go']['main']['App']['GetModuleOrder']();
}

export function GetNotes(arg1) {
  return window['go']['main']['App']['GetNotes'](arg1);
}

export function GetNotifications(arg1) {
  return window['go']['main']['App']['GetNotifications'](arg1);
}

export function GetPinnedTerminals() {
  return window['go']['main']['App']['GetPinnedTerminals']();
}

export function GetPomodoroSettings() {
  return window['go']['main']['App']['GetPomodoroSettings']();
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjectDependencies(arg1) {
  return window['go']['main']['App']['GetProjectDependencies'](arg1);
}

export function GetProjectFolderHierarchy(arg1) {
  return window['go']['main']['App']['GetProjectFolderHierarchy'](arg1);
}

export function GetProjectGroups() {
  return window['go']['main']['App']['GetProjectGroups']();
}

export function GetProjectPrompts(arg1) {
  return window['go']['main']['App']['GetProjectPrompts'](arg1);
}

export function GetProjectStructure(arg1) {
  return window['go']['main']['App']['GetProjectStructure'](arg1);
}

export function GetProjectWidgets(arg1) {
  return window['go']['main']['App']['GetProjectWidgets'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetPromptCategories(arg1) {
  return window['go']['main']['App']['GetPromptCategories'](arg1);
}

export function GetRunners() {
  return window['go']['main']['App']['GetRunners']();
}

export function GetSelectedHealthReport(arg1) {
  return window['go']['main']['App']['GetSelectedHealthReport'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetTerminalAccounts() {
  return window['go']['main']['App']['GetTerminalAccounts']();
}

export function GetTerminalFontSize() {
  return window['go']['main']['App']['GetTerminalFontSize']();
}

export function GetTerminalNameOverrides() {
  return window['go']['main']['App']['GetTerminalNameOverrides']();
}

export function GetTerminalRunners() {
  return window['go']['main']['App']['GetTerminalRunners']();
}

export function GetTerminalTheme() {
  return window['go']['main']['App']['GetTerminalTheme']();
}

export function GetTranscriptionEngine() {
  return window['go']['main']['App']['GetTranscriptionEngine']();
}

export function GetUnreadNotificationCount() {
  return window['go']['main']['App']['GetUnreadNotificationCount']();
}

export function GetVoiceAutoSubmit() {
  return window['go']['main']['App']['GetVoiceAutoSubmit']();
}

export function GetVoiceLang() {
  return window['go']['main']['App']['GetVoiceLang']();
}

export function GetWidgetSettings() {
  return window['go']['main']['App']['GetWidgetSettings']();
}

export function GmailAddAccount(arg1, arg2) {
  return window['go']['main']['App']['GmailAddAccount'](arg1, arg2);
}

export function GmailCreateDraft(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GmailCreateDraft'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GmailDeleteDraft(arg1, arg2) {
  return window['go']['main']['App']['GmailDeleteDraft'](arg1, arg2);
}

export function GmailGetAttachment(arg1, arg2, arg3) {
  return window['go']['main']['App']['GmailGetAttachment'](arg1, arg2, arg3);
}

export function GmailGetSignature(arg1) {
  return window['go']['main']['App']['GmailGetSignature'](arg1);
}

export function GmailGetThread(arg1, arg2) {
  return window['go']['main']['App']['GmailGetThread'](arg1, arg2);
}

export function GmailInboxUnread(arg1) {
  return window['go']['main']['App']['GmailInboxUnread'](arg1);
}

export function GmailInstallMcp() {
  return window['go']['main']['App']['GmailInstallMcp']();
}

export function GmailListContacts(arg1) {
  return window['go']['main']['App']['GmailListContacts'](arg1);
}

export function GmailListLabels(arg1) {
  return window['go']['main']['App']['GmailListLabels'](arg1);
}

export function GmailListThreadDrafts(arg1, arg2) {
  return window['go']['main']['App']['GmailListThreadDrafts'](arg1, arg2);
}

export function GmailListThreads(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GmailListThreads'](arg1, arg2, arg3, arg4);
}

export function GmailMcpInstalled() {
  return window['go']['main']['App']['GmailMcpInstalled']();
}

export function GmailModifyThread(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GmailModifyThread'](arg1, arg2, arg3, arg4);
}

export function GmailOpenAttachment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GmailOpenAttachment'](arg1, arg2, arg3, arg4);
}

export function GmailPickAttachments() {
  return window['go']['main']['App']['GmailPickAttachments']();
}

export function GmailReauthAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['GmailReauthAccount'](arg1, arg2, arg3);
}

export function GmailRemoveAccount(arg1) {
  return window['go']['main']['App']['GmailRemoveAccount'](arg1);
}

export function GmailSaveAttachment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GmailSaveAttachment'](arg1, arg2, arg3, arg4);
}

export function GmailSendDraft(arg1, arg2) {
  return window['go']['main']['App']['GmailSendDraft'](arg1, arg2);
}

export function GmailSendMessage(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GmailSendMessage'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GmailSetAccountMcp(arg1, arg2) {
  return window['go']['main']['App']['GmailSetAccountMcp'](arg1, arg2);
}

export function GmailTrashThread(arg1, arg2) {
  return window['go']['main']['App']['GmailTrashThread'](arg1, arg2);
}

export function GmailUntrashThread(arg1, arg2) {
  return window['go']['main']['App']['GmailUntrashThread'](arg1, arg2);
}

export function GmailUpdateDraft(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['GmailUpdateDraft'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function IncrementPromptUsage(arg1, arg2, arg3) {
  return window['go']['main']['App']['IncrementPromptUsage'](arg1, arg2, arg3);
}

export function IsDevMode() {
  return window['go']['main']['App']['IsDevMode']();
}

export function IsGitRepo(arg1) {
  return window['go']['main']['App']['IsGitRepo'](arg1);
}

export function KillClaudeSession(arg1, arg2) {
  return window['go']['main']['App']['KillClaudeSession'](arg1, arg2);
}

export function LaunchITerm() {
  return window['go']['main']['App']['LaunchITerm']();
}

export function ListProjectRepos(arg1) {
  return window['go']['main']['App']['ListProjectRepos'](arg1);
}

export function Log(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Log'](arg1, arg2, arg3, arg4);
}

export function MarkNotificationRead(arg1) {
  return window['go']['main']['App']['MarkNotificationRead'](arg1);
}

export function MoveKanbanTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MoveKanbanTask'](arg1, arg2, arg3, arg4);
}

export function OpenAddonsDir() {
  return window['go']['main']['App']['OpenAddonsDir']();
}

export function OpenProjectTask(arg1, arg2) {
  return window['go']['main']['App']['OpenProjectTask'](arg1, arg2);
}

export function OpenTmuxInITerm(arg1) {
  return window['go']['main']['App']['OpenTmuxInITerm'](arg1);
}

export function PasteClipboardToSession(arg1) {
  return window['go']['main']['App']['PasteClipboardToSession'](arg1);
}

export function PathExists(arg1) {
  return window['go']['main']['App']['PathExists'](arg1);
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function RenameITermTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameITermTab'](arg1, arg2, arg3);
}

export function RenameITermTabBySessionID(arg1, arg2) {
  return window['go']['main']['App']['RenameITermTabBySessionID'](arg1, arg2);
}

export function RequestStyledHistory(arg1) {
  return window['go']['main']['App']['RequestStyledHistory'](arg1);
}

export function ResetVoiceRecognition() {
  return window['go']['main']['App']['ResetVoiceRecognition']();
}

export function RunAutomationRule(arg1) {
  return window['go']['main']['App']['RunAutomationRule'](arg1);
}

export function SaveAutomationRule(arg1) {
  return window['go']['main']['App']['SaveAutomationRule'](arg1);
}

export function SaveCustomHealthCheck(arg1) {
  return window['go']['main']['App']['SaveCustomHealthCheck'](arg1);
}

export function SaveDashboard(arg1) {
  return window['go']['main']['App']['SaveDashboard'](arg1);
}

export function SaveFileContent(arg1, arg2) {
  return window['go']['main']['App']['SaveFileContent'](arg1, arg2);
}

export function SaveKanbanColumns(arg1, arg2) {
  return window['go']['main']['App']['SaveKanbanColumns'](arg1, arg2);
}

export function SaveNotes(arg1, arg2) {
  return window['go']['main']['App']['SaveNotes'](arg1, arg2);
}

export function SavePomodoroSettings(arg1, arg2) {
  return window['go']['main']['App']['SavePomodoroSettings'](arg1, arg2);
}

export function SaveRunner(arg1) {
  return window['go']['main']['App']['SaveRunner'](arg1);
}

export function SaveScreenshot(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveScreenshot'](arg1, arg2, arg3);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SendITermSpecialKey(arg1, arg2) {
  return window['go']['main']['App']['SendITermSpecialKey'](arg1, arg2);
}

export function SetActiveProject(arg1) {
  return window['go']['main']['App']['SetActiveProject'](arg1);
}

export function SetAddonEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetAddonEnabled'](arg1, arg2);
}

export function SetAgentSkillEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetAgentSkillEnabled'](arg1, arg2);
}

export function SetAllViewFontSize(arg1) {
  return window['go']['main']['App']['SetAllViewFontSize'](arg1);
}

export function SetAutomationRuleEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetAutomationRuleEnabled'](arg1, arg2);
}

export function SetClaudeAccounts(arg1) {
  return window['go']['main']['App']['SetClaudeAccounts'](arg1);
}

export function SetDashboardFullscreen(arg1) {
  return window['go']['main']['App']['SetDashboardFullscreen'](arg1);
}

export function SetDefaultRunner(arg1) {
  return window['go']['main']['App']['SetDefaultRunner'](arg1);
}

export function SetElevenLabsAPIKey(arg1) {
  return window['go']['main']['App']['SetElevenLabsAPIKey'](arg1);
}

export function SetGlobalPromptPrefix(arg1) {
  return window['go']['main']['App']['SetGlobalPromptPrefix'](arg1);
}

export function SetGlobalPromptSuffix(arg1) {
  return window['go']['main']['App']['SetGlobalPromptSuffix'](arg1);
}

export function SetGmailConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetGmailConfig'](arg1, arg2, arg3);
}

export function SetGmailMcpEnabled(arg1) {
  return window['go']['main']['App']['SetGmailMcpEnabled'](arg1);
}

export function SetHealthSelection(arg1, arg2) {
  return window['go']['main']['App']['SetHealthSelection'](arg1, arg2);
}

export function SetHiddenModules(arg1) {
  return window['go']['main']['App']['SetHiddenModules'](arg1);
}

export function SetJiraSettings(arg1) {
  return window['go']['main']['App']['SetJiraSettings'](arg1);
}

export function SetManualCheck(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetManualCheck'](arg1, arg2, arg3, arg4);
}

export function SetModuleOrder(arg1) {
  return window['go']['main']['App']['SetModuleOrder'](arg1);
}

export function SetPinnedTerminal(arg1, arg2) {
  return window['go']['main']['App']['SetPinnedTerminal'](arg1, arg2);
}

export function SetProjectJira(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetProjectJira'](arg1, arg2, arg3);
}

export function SetProjectWidgets(arg1, arg2) {
  return window['go']['main']['App']['SetProjectWidgets'](arg1, arg2);
}

export function SetTermViewSize(arg1, arg2) {
  return window['go']['main']['App']['SetTermViewSize'](arg1, arg2);
}

export function SetTerminalAccount(arg1, arg2) {
  return window['go']['main']['App']['SetTerminalAccount'](arg1, arg2);
}

export function SetTerminalFontSize(arg1) {
  return window['go']['main']['App']['SetTerminalFontSize'](arg1);
}

export function SetTerminalNameOverride(arg1, arg2) {
  return window['go']['main']['App']['SetTerminalNameOverride'](arg1, arg2);
}

export function SetTerminalRunner(arg1, arg2) {
  return window['go']['main']['App']['SetTerminalRunner'](arg1, arg2);
}

export function SetTerminalTheme(arg1) {
  return window['go']['main']['App']['SetTerminalTheme'](arg1);
}

export function SetTranscriptionEngine(arg1) {
  return window['go']['main']['App']['SetTranscriptionEngine'](arg1);
}

export function SetVoiceAutoSubmit(arg1) {
  return window['go']['main']['App']['SetVoiceAutoSubmit'](arg1);
}

export function SetVoiceLang(arg1) {
  return window['go']['main']['App']['SetVoiceLang'](arg1);
}

export function SetWidgetSettings(arg1) {
  return window['go']['main']['App']['SetWidgetSettings'](arg1);
}

export function StartVoiceRecognition(arg1) {
  return window['go']['main']['App']['StartVoiceRecognition'](arg1);
}

export function StopVoiceRecognition() {
  return window['go']['main']['App']['StopVoiceRecognition']();
}

export function SwitchITermTab(arg1, arg2) {
  return window['go']['main']['App']['SwitchITermTab'](arg1, arg2);
}

export function SwitchITermTabBySessionID(arg1) {
  return window['go']['main']['App']['SwitchITermTabBySessionID'](arg1);
}

export function SyncJiraBoard(arg1) {
  return window['go']['main']['App']['SyncJiraBoard'](arg1);
}

export function TestJiraConnection(arg1) {
  return window['go']['main']['App']['TestJiraConnection'](arg1);
}

export function TogglePromptPinned(arg1, arg2, arg3) {
  return window['go']['main']['App']['TogglePromptPinned'](arg1, arg2, arg3);
}

export function UnwatchITermSession() {
  return window['go']['main']['App']['UnwatchITermSession']();
}

export function UpdateGlobalPrompt(arg1, arg2) {
  return window['go']['main']['App']['UpdateGlobalPrompt'](arg1, arg2);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function UpdateProjectGroup(arg1) {
  return window['go']['main']['App']['UpdateProjectGroup'](arg1);
}

export function UpdateProjectTask(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectTask'](arg1, arg2);
}

export function UpdatePrompt(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePrompt'](arg1, arg2, arg3);
}

export function UpsertKanbanTask(arg1, arg2) {
  return window['go']['main']['App']['UpsertKanbanTask'](arg1, arg2);
}

export function WatchITermSession(arg1) {
  return window['go']['main']['App']['WatchITermSession'](arg1);
}

export function WriteITermText(arg1, arg2) {
  return window['go']['main']['App']['WriteITermText'](arg1, arg2);
}

export function WriteITermTextBySessionID(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteITermTextBySessionID'](arg1, arg2, arg3);
}
